---
title: "STAT 8020 Classification R Demo"
author: "Whitney"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 2
    fig_width: 8.5
    fig_height: 8
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ISLR)
names(Smarket)
summary(Smarket)
pairs(Smarket, col = Smarket$Direction,
      cex = 0.5)
```

## Logistic regression

```{r}
LogisticFit <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, data = Smarket,
                   family = binomial)
summary(LogisticFit)
LogisticProbs <- predict(LogisticFit, type = "response") 
LogisticProbs[1:5]
LogisticPred <- ifelse(LogisticProbs > 0.5, "Up", "Down")
attach(Smarket)
table(LogisticPred, Direction)
mean(LogisticPred == Direction)
```

## Make training and test set

```{r}
train = Year < 2005
LogisticFit1 <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, data = Smarket,
                    family = binomial, subset = train)
LogisticProbs1 <- predict(LogisticFit1,
                          newdata = Smarket[!train,], type = "response") 
LogisticPred1 <- ifelse(LogisticProbs1 > 0.5, "Up", "Down")
Direction.2005 <- Smarket$Direction[!train]
table(LogisticPred1, Direction.2005)
mean(LogisticPred1 == Direction.2005)
```

## Fit smaller model

```{r}
LogisticFit2 <- glm(Direction ~ Lag1 + Lag2,
            data = Smarket, family = binomial, subset = train)
LogisticProbs2 <- predict(LogisticFit2, newdata = Smarket[!train,], type = "response") 
LogisticPred2 <- ifelse(LogisticProbs2 > 0.5, "Up", "Down")
table(LogisticPred2, Direction.2005)
mean(LogisticPred2 == Direction.2005)
```

## Linear Discriminant Analysis

```{r}
library(MASS)
ldaFit <- lda(Direction ~ Lag1 + Lag2, data = Smarket, subset = Year < 2005)
ldaFit
Smarket.2005 <- subset(Smarket, Year == 2005)
ldaPred <- predict(ldaFit, Smarket.2005)
class(ldaPred)
data.frame(ldaPred)[1:5,]
table(ldaPred$class, Smarket.2005$Direction)
mean(ldaPred$class == Smarket.2005$Direction)
```

## K-Nearest Neighbors

```{r, message=FALSE}
library(class)
attach(Smarket)
Xlag <- cbind(Lag1, Lag2)
train <- Year < 2005
knnPred <- knn(Xlag[train,], Xlag[!train,], Direction[train], k = 1)
table(knnPred, Direction[!train])
mean(knnPred == Direction[!train])

knn3Pred <- knn(Xlag[train,], Xlag[!train,], Direction[train], k = 3)
table(knn3Pred, Direction[!train])
mean(knn3Pred == Direction[!train])
```




