---
title: "STAT 8020 Lecture 12 R demo"
author: "Whitney"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 3
    fig_width: 8.5
    fig_height: 8
    fig_caption: yes
header-includes:
   - \usepackage{animate}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Model Selection

### All subset selection

```{r}
library(faraway)
library(tidyverse)
library(caret)
library(leaps)
models <- regsubsets(Species ~ Area + Elevation + Nearest + Scruz + Adjacent, data = gala, nvmax = 5)
summary(models)
```

### Some model selection criteria
 
```{r}
res.sum <- summary(models)
R2 <- res.sum$rsq
par(las = 1)
plot(1:5, R2, pch = 16, xlab = "p",
     col = "blue", ylab = expression(R^2))
lines(1:5, R2, lty = 2)
Adj.R2 <- res.sum$adjr2
plot(1:5, Adj.R2, pch = 16, xlab = "p",
     col = "blue", ylab = expression(R[adj]^2))
lines(1:5, Adj.R2, lty = 2)
Cp <- res.sum$cp
par(las = 1)
plot(1:5, Cp, pch = 16, xlab = "p",
     col = "blue", ylab = expression(C[p]))
lines(1:5, Cp, lty = 2)
BIC <- res.sum$bic
par(las = 1)
plot(1:5, BIC, pch = 16, xlab = "p",
     col = "blue", ylab = "BIC")
lines(1:5, BIC, lty = 2)
```

### Stepwise Selection

```{r}
full <- lm(Species ~ Area + Elevation + Nearest + Scruz + Adjacent,
           data = gala)
step_gala <- step(full)
```


## Diagnostics in Multiple Linear Regression

###Residuals and Leverage

```{r}
step_gala$residuals

par(las = 1)
plot(step_gala$res, pch = 16,
     cex = 0.8, col = "blue",
     ylab = "Residuals",
     main = "Index plot of residuals")
abline(h = 0, lty = 2, col = "gray")

par(las = 1)
x <- model.matrix(step_gala)
lev <- hat(x)
plot(lev, ylab="Leverages", pch = 16,
     cex = 0.8, col = "blue",
     main="Index plot of Leverages")
abline(h = (2 * 3) / 30, col = "gray")
sum(lev)

names(lev) <- row.names(gala)
lev[lev > 0.2]
```

###Studentized Residuals

```{r}
gs <- summary(step_gala)
gs$sig


studRes <- gs$res / (gs$sig * sqrt(1 - lev))

par(las = 1)
plot(studRes, pch = 16,
     cex = 0.8, col = "blue",
     ylab = expression(r[i]), main = "Studentized Residuals")
abline(h = 0, lty = 2, col = "gray")
```

###Identifying Influential Observations: DFFITS
```{r, message=F}
library(olsrr)
ols_plot_dffits(step_gala)
```





















