---
title: "STAT 8020 Lecture 9 R demo"
author: "Whitney"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 2
    fig_width: 8.5
    fig_height: 8
    fig_caption: yes
header-includes:
   - \usepackage{animate}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Multiple Linear Regression Example

```{r}
library(faraway)
data(gala)
attach(gala)
summary(gala)
pairs(gala, cex = 0.5, col = "blue")
cor(gala)

mod <- lm(Species ~ Elevation + Adjacent, data = gala)
plot(mod$fitted.values, Species, pch = 16, col = "blue")
abline(0, 1, col = "red")

plot(mod$fitted.values, mod$residuals, pch = 16, col = "blue")
abline(h = 0, col = "red")

par(las = 1)
hist(mod$residuals, 12, prob = T,
     col = "lightblue", border = "gray")
xg <- seq(-200, 200, 1)
yg <- dnorm(xg, 0, 60.86)
lines(xg, yg)


plot(qnorm(1:30 / 31, 0, 60.86), sort(mod$residuals), pch = 16,
     col = "gray", xlab = "Normal Quantiles", ylab = "Residuals")
abline(0, 1)

```


```{r, message=FALSE}
Elev_grid <- seq(25, max(Elevation), 20)
Adj_grid <- seq(0.03, 4670, 20)
x_grid <- expand.grid(Elev_grid, Adj_grid)
beta <- mod$coefficients
Spec_est <- beta[1] + x_grid[, 1] * beta[2] + x_grid[, 2] * beta[3]

library(fields)
image.plot(Elev_grid, Adj_grid, matrix(Spec_est, nrow = length(Elev_grid),
                                       ncol = length(Adj_grid)))
points(Elevation, Adjacent, pch = "*", cex = 1.2)


new_island <- data.frame(Elevation = 275, Adjacent = 300)
predict(mod, new_island, interval = "confidence") 
predict(mod, new_island, interval = "predict") 
```

## Model Selection

```{r}
library(tidyverse)
library(caret)
library(leaps)
models <- regsubsets(Species ~ Area + Elevation + Nearest + Scruz + Adjacent, data = gala, nvmax = 5)
summary(models)

res.sum <- summary(models)
data.frame(
  Adj.R2 = which.max(res.sum$adjr2),
  CP = which.min(res.sum$cp),
  BIC = which.min(res.sum$bic)
)
full <- lm(Species ~ Area + Elevation + Nearest + Scruz + Adjacent,
           data = gala)
step(full)
```

















